# Generated by Django 5.2.8 on 2025-11-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('duration', models.PositiveIntegerField(db_index=True, help_text='Duration/distance (int)')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='routes.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='routes.airport')),
            ],
            options={
                'indexes': [models.Index(fields=['from_airport', 'position'], name='routes_rout_from_ai_cd9770_idx'), models.Index(fields=['duration'], name='routes_rout_duratio_4d4ed3_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_airport', 'position'), name='unique_from_position')],
            },
        ),
    ]
